module Api::V1
  class HostsController < ApiController
  before_action :set_host, only: [:show, :update, :destroy]

  # GET /hosts
  # GET /hosts.json
  def index
    @hosts = Host.all
  end

  # GET /hosts/1
  # GET /hosts/1.json
  def show
  end

  # !! not used, generated by scaffold !!
  # POST /hosts
  # POST /hosts.json
  def create
    @host = Host.new(host_params)

    if @host.save
      render :show, status: :created, location: @host
    else
      render json: @host.errors, status: :unprocessable_entity
    end
  end

  # !! not used, generated by scaffold !!
  # PATCH/PUT /hosts/1
  # PATCH/PUT /hosts/1.json
  def update
    if @host.update(host_params)
      render :show, status: :ok, location: @host
    else
      render json: @host.errors, status: :unprocessable_entity
    end
  end

  # !! not used, generated by scaffold !!
  # DELETE /hosts/1
  # DELETE /hosts/1.json
  def destroy
    @host.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_host
      @host = Host.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def host_params
      params.require(:host).permit(:name)
    end
   end
end
